[package]
name = "cdc-producer"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow = "1.0.104"
rdkafka = "0.39.0"
thiserror = "2.0.20"
tokio = {version = "1.53.1", features = ["full"]}
cdc-avro = {path = "../cdc-avro"}
cdc-wal-reader = {path="../cdc-wal-reader"}
config = "0.15.25"
serde = { version = "1.0.229", features = ["derive"] }
bumpalo = { version = "3.20.3", features = ["collections"] }
futures-util = "0.3.34"
metric = "0.1.2"
metrics = "0.24.6"
metrics-exporter-prometheus = "0.18.3"
