[package]
name = "cdc-wal-reader"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow = "1.0.104"
apache-avro = "0.22.0"
bytes = "1.12.1"
pgwire-replication = "0.4.0"
serde = { version = "1.0.229", features = ["derive"] }
tokio = {version = "1.53.1", features = ["full"]}
cdc-avro = {path = "../cdc-avro"}
thiserror = "2.0.20"
tokio-postgres = "0.7.18"

# Simd version
memchr = "2.8.3"
simdutf8 = "0.1.5"

# Pre alloc vec
bumpalo = { version = "3.20.3", features = ["collections", "serde"] }

# Faster hash
ahash = "0.8.12"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }


[[bench]]
name = "decoding"
harness = false

[[bench]]
name = "insert"
harness = false
