[package]
name = "postgres-connector"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
rdkafka = "0.39.0"
tokio = { version = "1.53.1", features = ["full"] }
tokio-postgres = "0.7.18"
cdc-avro = {path = "../cdc-avro"}
cdc-sink = {path = "../cdc-sink"}
config = "0.15.25"
serde = { version = "1.0.229", features = ["derive"] }
thiserror = "2.0.20"
