[package]
name = "cdc-sink"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
rdkafka = "0.39.0"
tokio = { version = "1.53.1", features = ["full"] }
tokio-postgres = "0.7.18"
cdc-avro = {path = "../cdc-avro"}
futures-util = "0.3.34"
serde = { version = "1.0.229", features = ["derive"] }
ahash = "0.8.12"
bumpalo = "3.20.3"
metrics = "0.24.6"
chrono = "0.4.45"
metrics-exporter-prometheus = "0.18.3"
